version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
        - ${DOCKER_ROOT}/sonarr:/config
        - ${MEDIA_ROOT}/tv:/tv
        - ${DL_DIR}:/downloads
    ports:
        - ${SONARR_PORT}:8989
    restart: unless-stopped
    networks:
      - media

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/radarr:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${DL_DIR}:/downloads
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    networks:
      - media

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/jackett:/config
      - ${DL_DIR}:/downloads
    ports:
      - ${JACKETT_PORT}:9117
    restart: unless-stopped
    networks:
      - media

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_ROOT}/sabnzbd:/config
      - ${DL_DIR}:/downloads
      - ${DL_DIR}/incomplete:/incomplete-downloads
    ports:
      - ${SABNZBD_PORT}:8080
    restart: unless-stopped
    networks:
      - media

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${DOCKER_ROOT}/deluge:/config
      - ${DL_DIR}:/downloads
    ports:
      - ${DELUGE_PORT}:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - media
      
networks:
  media:
